In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url='https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
headers={
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"
}
page=requests.get(url, headers=headers)
soup=BeautifulSoup(page.content, 'html.parser')

In [ ]:
print (soup)

In [39]:
soup.find_all('table')[1]

<table class="wikitable sortable" id="mwBQA">
<tbody id="mwBQE"><tr id="mwBQI"><th id="mwBQM">Rank</th>
<th id="mwBQQ">Name</th>
<th id="mwBQU">Industry</th>
<th id="mwBQY">Revenue <br id="mwBQc"/>(USD billions)</th>
<th id="mwBQg">Employees</th>
<th id="mwBQk">Headquarters</th></tr>
<tr id="mwBQo">
<td id="mwBQs">1</td>
<td id="mwBQw"><a href="//en.wikipedia.org/wiki/Cargill" id="mwBQ0" rel="mw:WikiLink" title="Cargill">Cargill</a></td>
<td id="mwBQ4">Food &amp; Drink</td>
<td id="mwBQ8" style="text-align:center;">154</td>
<td id="mwBRA" style="text-align:center;">155,000</td>
<td id="mwBRE"><a href="//en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwBRI" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwBRM">
<td id="mwBRQ">2</td>
<td id="mwBRU"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Koch_Industries" id="mwBRY" rel="mw:WikiLink" title="Koch Industries">Koch</a></td>
<td id="mwBRc">Multicompany</td>
<td id="mwBRg" style="text-align:center;">125</td>
<td id="mwBRk" style="text-align:center;">120,000</td>
<td id="mwBRo"><a href="//en.wikipedia.org/wiki/Wichita,_Kansas" id="mwBRs" rel="mw:WikiLink" title="Wichita, Kansas">Wichita, Kansas</a></td></tr>
<tr id="mwBRw">
<td id="mwBR0">3</td>
<td id="mwBR4"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Publix_Super_Markets" id="mwBR8" rel="mw:WikiLink" title="Publix Super Markets">Publix Super Markets</a></td>
<td id="mwBSA">Food Markets</td>
<td id="mwBSE" style="text-align:center;">59.7</td>
<td id="mwBSI" style="text-align:center;">260,000</td>
<td id="mwBSM"><a href="//en.wikipedia.org/wiki/Lakeland,_Florida" id="mwBSQ" rel="mw:WikiLink" title="Lakeland, Florida">Lakeland, Florida</a></td></tr>
<tr id="mwBSU">
<td id="mwBSY">4</td>
<td id="mwBSc"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Mars,_Incorporated" id="mwBSg" rel="mw:WikiLink" title="Mars, Incorporated">Mars</a></td>
<td id="mwBSk">Food &amp; Drink</td>
<td id="mwBSo" style="text-align:center;">55</td>
<td id="mwBSs" style="text-align:center;">150,000</td>
<td id="mwBSw"><a href="//en.wikipedia.org/wiki/McLean,_Virginia" id="mwBS0" rel="mw:WikiLink" title="McLean, Virginia">McLean, Virginia</a></td></tr>
<tr id="mwBS4">
<td id="mwBS8">5</td>
<td id="mwBTA"><a href="//en.wikipedia.org/wiki/H-E-B" id="mwBTE" rel="mw:WikiLink" title="H-E-B">H-E-B Grocery Company</a></td>
<td id="mwBTI">Food Markets</td>
<td id="mwBTM" style="text-align:center;">49.57</td>
<td id="mwBTQ" style="text-align:center;">175,000</td>
<td id="mwBTU"><a class="mw-redirect" href="//en.wikipedia.org/wiki/San_Antonio,_Texas" id="mwBTY" rel="mw:WikiLink" title="San Antonio, Texas">San Antonio, Texas</a></td></tr>
<tr id="mwBTc">
<td id="mwBTg">6</td>
<td id="mwBTk"><a href="//en.wikipedia.org/wiki/Reyes_Holdings" id="mwBTo" rel="mw:WikiLink" title="Reyes Holdings">Reyes Holdings</a></td>
<td id="mwBTs">Food, Drink &amp; Tobacco</td>
<td id="mwBTw" style="text-align:center;">44</td>
<td id="mwBT0" style="text-align:center;">36,000</td>
<td id="mwBT4"><a href="//en.wikipedia.org/wiki/Rosemont,_Illinois" id="mwBT8" rel="mw:WikiLink" title="Rosemont, Illinois">Rosemont, Illinois</a></td></tr>
<tr id="mwBUA">
<td id="mwBUE">7</td>
<td id="mwBUI"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Enterprise_Mobility" id="mwBUM" rel="mw:WikiLink" title="Enterprise Mobility">Enterprise Mobility</a></td>
<td id="mwBUQ">Services</td>
<td id="mwBUU" style="text-align:center;">38</td>
<td id="mwBUY" style="text-align:center;">100,000</td>
<td id="mwBUc"><a href="//en.wikipedia.org/wiki/Clayton,_Missouri" id="mwBUg" rel="mw:WikiLink" title="Clayton, Missouri">Clayton, Missouri</a></td></tr>
<tr id="mwBUk">
<td id="mwBUo">8</td>
<td id="mwBUs"><a href="//en.wikipedia.org/wiki/Fidelity_Investments" id="mwBUw" rel="mw:WikiLink" title="Fidelity Investments">Fidelity Investments</a></td>
<td id="mwBU0">Insurance</td>
<td id="mwBU4" style="text-align:center;">32.7</td>
<td id="mwBU8" style="text-align:center;">78,000</td>
<td id="mwBVA"><a href="//en.wikipedia.org/wiki/Boston" id="mwBVE" rel="mw:WikiLink" title="Boston">Boston, Massachusetts</a></td></tr>
<tr id="mwBVI">
<td id="mwBVM">9</td>
<td id="mwBVQ"><a href="//en.wikipedia.org/wiki/Southern_Glazer's_Wine_and_Spirits" id="mwBVU" rel="mw:WikiLink" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine &amp; Spirits</a></td>
<td id="mwBVY">Food, Drink &amp; Tobacco</td>
<td id="mwBVc" style="text-align:center;">25</td>
<td id="mwBVg" style="text-align:center;">24,000</td>
<td id="mwBVk"><a href="//en.wikipedia.org/wiki/Miramar,_Florida" id="mwBVo" rel="mw:WikiLink" title="Miramar, Florida">Miramar, Florida</a></td></tr>
<tr id="mwBVs">
<td id="mwBVw">10</td>
<td id="mwBV0"><a href="//en.wikipedia.org/wiki/Cox_Enterprises" id="mwBV4" rel="mw:WikiLink" title="Cox Enterprises">Cox Enterprises</a></td>
<td id="mwBV8">Media</td>
<td id="mwBWA" style="text-align:center;">23.5</td>
<td id="mwBWE" style="text-align:center;">50,000</td>
<td id="mwBWI"><a href="//en.wikipedia.org/wiki/Atlanta" id="mwBWM" rel="mw:WikiLink" title="Atlanta">Atlanta, Georgia</a></td></tr>
</tbody></table>

In [40]:
table=soup.find('table', class_='wikitable sortable')
print(table)

<table class="wikitable sortable" id="mwOw">
<caption id="mwPA"></caption>
<tbody id="mwPQ"><tr id="mwPg"><th id="mwPw">Rank</th>
<th id="mwQA">Name</th>
<th id="mwQQ">Industry</th>
<th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>
<th id="mwRA">Revenue growth</th>
<th id="mwRQ">Employees</th>
<th id="mwRg">Headquarters</th></tr>
<tr id="mwRw">
<td id="mwSA">1</td>
<td id="mwSQ"><a href="//en.wikipedia.org/wiki/Walmart" id="mwSg" rel="mw:WikiLink" title="Walmart">Walmart</a></td>
<td id="mwSw">Retail</td>
<td id="mwTA" style="text-align:center;">680,985</td>
<td id="mwTQ" style="text-align:center;"><span about="#mwt7" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwTg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt8" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwTw" style="display:none" typeof="mw:Transclusion"></span> 5.1%</td>
<td id="mwUA" style="text-align:center;">2,100,000</td>
<td id="mwUQ"><a href="//en.wikipedia.org/wiki/Bentonville,_Arkansas" id="mwUg" rel="mw:WikiLink" title="Bentonville, Arkansas">Bentonville, Arkansas</a></td></tr>
<tr id="mwUw">
<td id="mwVA">2</td>
<td id="mwVQ"><a href="//en.wikipedia.org/wiki/Amazon_(company)" id="mwVg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td>
<td id="mwVw">Retail and cloud computing</td>
<td id="mwWA" style="text-align:center;">637,959</td>
<td id="mwWQ" style="text-align:center;"><span about="#mwt9" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt10" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwWw" style="display:none" typeof="mw:Transclusion"></span> 11.0%</td>
<td id="mwXA" style="text-align:center;">1,556,000</td>
<td id="mwXQ"><a href="//en.wikipedia.org/wiki/Seattle" id="mwXg" rel="mw:WikiLink" title="Seattle">Seattle, Washington</a></td></tr>
<tr id="mwXw">
<td id="mwYA">3</td>
<td id="mwYQ"><a href="//en.wikipedia.org/wiki/UnitedHealth_Group" id="mwYg" rel="mw:WikiLink" title="UnitedHealth Group">UnitedHealth Group</a></td>
<td id="mwYw">Healthcare</td>
<td id="mwZA" style="text-align:center;">400,278</td>
<td id="mwZQ" style="text-align:center;"><span about="#mwt11" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwZg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt12" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwZw" style="display:none" typeof="mw:Transclusion"></span> 7.7%</td>
<td id="mwaA" style="text-align:center;">400,000</td>
<td id="mwaQ"><a href="//en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwag" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwaw">
<td id="mwbA">4</td>
<td id="mwbQ"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Apple_Inc" id="mwbg" rel="mw:WikiLink" title="Apple Inc">Apple</a></td>
<td id="mwbw">Technology</td>
<td id="mwcA" style="text-align:center;">391,035</td>
<td id="mwcQ" style="text-align:center;"><span about="#mwt13" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwcg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt14" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwcw" style="display:none" typeof="mw:Transclusion"></span> 2.0%</td>
<td id="mwdA" style="text-align:center;">164,000</td>
<td id="mwdQ"><a href="//en.wikipedia.org/wiki/Cupertino,_California" id="mwdg" rel="mw:WikiLink" title="Cupertino, California">Cupertino, California</a></td></tr>
<tr id="mwdw">
<td id="mweA">5</td>
<td id="mweQ"><a href="//en.wikipedia.org/wiki/CVS_Health" id="mweg" rel="mw:WikiLink" title="CVS Health">CVS Health</a></td>
<td id="mwew">Healthcare</td>
<td id="mwfA" style="text-align:center;">372,809</td>
<td id="mwfQ" style="text-align:center;"><span about="#mwt15" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwfg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt16" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwfw" style="display:none" typeof="mw:Transclusion"></span> 4.2%</td>
<td id="mwgA" style="text-align:center;">259,500</td>
<td id="mwgQ"><a href="//en.wikipedia.org/wiki/Woonsocket,_Rhode_Island" id="mwgg" rel="mw:WikiLink" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a></td></tr>
<tr id="mwgw">
<td id="mwhA">6</td>
<td id="mwhQ"><a href="//en.wikipedia.org/wiki/Berkshire_Hathaway" id="mwhg" rel="mw:WikiLink" title="Berkshire Hathaway">Berkshire Hathaway</a></td>
<td id="mwhw">Conglomerate</td>
<td id="mwiA" style="text-align:center;">371,433</td>
<td id="mwiQ" style="text-align:center;"><span about="#mwt17" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwig" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt18" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwiw" style="display:none" typeof="mw:Transclusion"></span> 1.9%</td>
<td id="mwjA" style="text-align:center;">392,400</td>
<td id="mwjQ"><a href="//en.wikipedia.org/wiki/Omaha,_Nebraska" id="mwjg" rel="mw:WikiLink" title="Omaha, Nebraska">Omaha, Nebraska</a></td></tr>
<tr id="mwjw">
<td id="mwkA">7</td>
<td id="mwkQ"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Alphabet_Inc" id="mwkg" rel="mw:WikiLink" title="Alphabet Inc">Alphabet</a></td>
<td id="mwkw">Technology and cloud computing</td>
<td id="mwlA" style="text-align:center;">350,018</td>
<td id="mwlQ" style="text-align:center;"><span about="#mwt19" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwlg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt20" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwlw" style="display:none" typeof="mw:Transclusion"></span> 13.9%</td>
<td id="mwmA" style="text-align:center;">183,323</td>
<td id="mwmQ"><a href="//en.wikipedia.org/wiki/Mountain_View,_California" id="mwmg" rel="mw:WikiLink" title="Mountain View, California">Mountain View, California</a></td></tr>
<tr id="mwmw">
<td id="mwnA">8</td>
<td id="mwnQ"><a href="//en.wikipedia.org/wiki/ExxonMobil" id="mwng" rel="mw:WikiLink" title="ExxonMobil">Exxon Mobil</a></td>
<td id="mwnw">Petroleum</td>
<td id="mwoA" style="text-align:center;">349,595</td>
<td id="mwoQ" style="text-align:center;"><span about="#mwt21" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwog" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt22" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwow" style="display:none" typeof="mw:Transclusion"></span> 1.5%</td>
<td id="mwpA" style="text-align:center;">60,900</td>
<td id="mwpQ"><a href="//en.wikipedia.org/wiki/Spring,_Texas" id="mwpg" rel="mw:WikiLink" title="Spring, Texas">Spring, Texas</a></td></tr>
<tr id="mwpw">
<td id="mwqA">9</td>
<td id="mwqQ"><a href="//en.wikipedia.org/wiki/McKesson_Corporation" id="mwqg" rel="mw:WikiLink" title="McKesson Corporation">McKesson Corporation</a></td>
<td id="mwqw">Healthcare</td>
<td id="mwrA" style="text-align:center;">308,951</td>
<td id="mwrQ" style="text-align:center;"><span about="#mwt23" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwrg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt24" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwrw" style="display:none" typeof="mw:Transclusion"></span> 11.7%</td>
<td id="mwsA" style="text-align:center;">48,000</td>
<td id="mwsQ"><a href="//en.wikipedia.org/wiki/Irving,_Texas" id="mwsg" rel="mw:WikiLink" title="Irving, Texas">Irving, Texas</a></td></tr>
<tr id="mwsw">
<td id="mwtA">10</td>
<td id="mwtQ"><a href="//en.wikipedia.org/wiki/Cencora" id="mwtg" rel="mw:WikiLink" title="Cencora">Cencora</a></td>
<td id="mwtw">Pharmacy wholesale</td>
<td id="mwuA" style="text-align:center;">293,959</td>
<td id="mwuQ" style="text-align:center;"><span about="#mwt25" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwug" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt26" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwuw" style="display:none" typeof="mw:Transclusion"></span> 12.1%</td>
<td id="mwvA" style="text-align:center;">44,000</td>
<td id="mwvQ"><a href="//en.wikipedia.org/wiki/Conshohocken,_Pennsylvania" id="mwvg" rel="mw:WikiLink" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a></td></tr>
<tr id="mwvw">
<td id="mwwA">11</td>
<td id="mwwQ"><a href="//en.wikipedia.org/wiki/JPMorgan_Chase" id="mwwg" rel="mw:WikiLink" title="JPMorgan Chase">JPMorgan Chase</a></td>
<td id="mwww">Financials</td>
<td id="mwxA" style="text-align:center;">278,906</td>
<td id="mwxQ" style="text-align:center;"><span about="#mwt27" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwxg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt28" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwxw" style="display:none" typeof="mw:Transclusion"></span> 16.5%</td>
<td id="mwyA" style="text-align:center;">317,233</td>
<td id="mwyQ"><a href="//en.wikipedia.org/wiki/New_York_City" id="mwyg" rel="mw:WikiLink" title="New York City">New York City, New York</a></td></tr>
<tr id="mwyw">
<td id="mwzA">12</td>
<td id="mwzQ"><a href="//en.wikipedia.org/wiki/Costco" id="mwzg" rel="mw:WikiLink" title="Costco">Costco Wholesale</a></td>
<td id="mwzw">Retail</td>
<td id="mw0A" style="text-align:center;">254,453</td>
<td id="mw0Q" style="text-align:center;"><span about="#mwt29" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw0g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt30" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw0w" style="display:none" typeof="mw:Transclusion"></span> 5.0%</td>
<td id="mw1A" style="text-align:center;">333,000</td>
<td id="mw1Q"><a href="//en.wikipedia.org/wiki/Issaquah,_Washington" id="mw1g" rel="mw:WikiLink" title="Issaquah, Washington">Issaquah, Washington</a></td></tr>
<tr id="mw1w">
<td id="mw2A">13</td>
<td id="mw2Q"><a class="mw-redirect" href="//en.wikipedia.org/wiki/Cigna" id="mw2g" rel="mw:WikiLink" title="Cigna">Cigna</a></td>
<td id="mw2w">Health insurance</td>
<td id="mw3A" style="text-align:center;">247,121</td>
<td id="mw3Q" style="text-align:center;"><span about="#mwt31" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw3g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt32" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw3w" style="display:none" typeof="mw:Transclusion"></span> 26.6%</td>
<td id="mw4A" style="text-align:center;">72,398</td>
<td id="mw4Q"><a href="//en.wikipedia.org/wiki/Bloomfield,_Connecticut" id="mw4g" rel="mw:WikiLink" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a></td></tr>
<tr id="mw4w">
<td id="mw5A">14</td>
<td id="mw5Q"><a href="//en.wikipedia.org/wiki/Microsoft" id="mw5g" rel="mw:WikiLink" title="Microsoft">Microsoft</a></td>
<td id="mw5w">Technology and cloud computing</td>
<td id="mw6A" style="text-align:center;">245,122</td>
<td id="mw6Q" style="text-align:center;"><span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw6g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="//en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt34" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw6w" style="display:none" typeof="mw:Transclusion"></span> 15.7%</td>
<td id="mw7A" style="text-align:center;">228,000</td>
<td id="mw7Q"><a href="//en.wikipedia.org/wiki/Redmond,_Washington" id="mw7g" rel="mw:WikiLink" title="Redmond, Washington">Redmond, Washington</a></td></tr>
<tr id="mw7w">
<td id="mw8A">15</td>

In [24]:
titles=table.find_all('th')
print(titles)

[<th id="mwPw">Rank</th>, <th id="mwQA">Name</th>, <th id="mwQQ">Industry</th>, <th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>, <th id="mwRA">Revenue growth</th>, <th id="mwRQ">Employees</th>, <th id="mwRg">Headquarters</th>]

In [25]:
table_titles=[title.text.strip() for title in titles]
print(table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [43]:
import pandas as pd

In [42]:
df=pd.DataFrame(columns= table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [41]:
column_data=table.find_all('tr')

In [44]:
for row in column_data[1:]:
    row_data=row.find_all('td')
    rowDAta=[data.text for data in row_data]
    length=len(df)
    df.loc[length] = rowDAta

In [45]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [47]:
df.to_csv(r'C:\Users\USER\Desktop\JKUAT_STAFFS\internal_attatchment\companie.csv',index=False)